version: "3.7"

services:
        nginx:
            build: ./requirements/nginx
            depends_on:
                - wordpress
            networks:
                - Inception_Network
            ports:
                - "443:443"
            volumes:
                - wordpress:/var/www/wordpress
            restart: always

        wordpress:
                build: ./requirements/wordpress
                depends_on: 
                    - mariadb
                networks:
                    - Inception_Network
                ports:
                    - "9000:9000"
                env_file:
                    - ./.env
                volumes:
                    - wordpress:/var/www/wordpress
                environment:
                    - DOMAIN_NAME=${DOMAIN_NAME}
                    - WP_TITLE=${WP_TITLE}
                    - WP_MAIL=${WP_MAIL}
                    - MYSQL_DATABASE=${MYSQL_DATABASE}
                    - MYSQL_USER=${MYSQL_USER}
                    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                    - MYSQL_HOST=${MYSQL_HOST}
                restart: always

        mariadb:
                build:
                  context: ./requirements/mariadb
                  args:
                    - MYSQL_DATABASE=${MYSQL_DATABASE}
                    - MYSQL_USER=${MYSQL_USER}
                    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
                    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                networks:
                    - Inception_Network
                ports:
                    - "3306:3306"
                volumes:
                    - mariadb:/var/lib/mysql
                restart: always

networks:
        Inception_Network:

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                    device: /home/${USER}/data/wordpress
                    o: bind
                    type: none
        mariadb:
                name: mariadb
                driver: local
                driver_opts:
                    device: /home/${USER}/data/mariadb
                    o: bind
                    type: none
