version: '3'
networks:
    inception:

volumes:
    wordpress: {}
        # driver: local
        # driver_opts:
        #     type: 'none'
        #     o: 'bind'
        #     device: '/Users/sbaranes/data/wordpress'
    dbdata: {}
        # driver: local
        # driver_opts:
        #     type: 'none'
        #     o: 'bind'
        #     device: '/Users/sbaranes/data/database'

services:
    mariadb:
        build: ./requirements/mariadb
        container_name: mariadb
        ports:
            - 3306:3306
        env_file: .env
        volumes:
            - dbdata:/var/lib/mysql
        restart: always
        networks:
            - inception

    wordpress:
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        container_name: wordpress
        ports:
            - 9000:9000
        env_file: .env
        volumes:
            - wordpress:/var/www/
        restart: always
        networks:
            - inception

    nginx:
        depends_on:
            - wordpress
        build: ./requirements/nginx
        container_name: nginx
        ports:
            - 443:443
        volumes:
            - wordpress:/var/www/
        restart: always
        networks:
            - inception
