ALTER USER root@localhost IDENTIFIED WITH mysql_native_password;
ALTER USER root@localhost IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
CREATE DATABASE MYSQL_DATABASE;
CREATE USER 'MYSQL_USER'@'%' identified by 'MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD';
FLUSH PRIVILEGES;
