sed -i 's/MYSQL_DATABASE/'${MYSQL_DATABASE}'/g' start_safe.sh
sed -i 's/MYSQL_USER/'${MYSQL_USER}'/g' start_safe.sh
sed -i 's/MYSQL_PASSWORD/'${MYSQL_PASSWORD}'/g' start_safe.sh
sed -i 's/MYSQL_PASSWORD/'${MYSQL_PASSWORD}'/g' start_safe.sh
sed -i 's/MYSQL_ROOT_PASSWORD/'${MYSQL_ROOT_PASSWORD}'/g' start_safe.sh
sed -i 's/MYSQL_ROOT_PASSWORD/'${MYSQL_ROOT_PASSWORD}'/g' start_safe.sh
sed -i 's/MYSQL_ROOT_PASSWORD/'${MYSQL_ROOT_PASSWORD}'/g' start_safe.sh
sed -i 's/MYSQL_ROOT_PASSWORD/'${MYSQL_ROOT_PASSWORD}'/g' start_safe.sh
sed -i 's/MYSQL_ROOT_PASSWORD/'${MYSQL_ROOT_PASSWORD}'/g' start_safe.sh
